[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  REDIRECT_URI = "https://mxrp.netlify.app"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200