[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "24"
  REDIRECT_URI = "https://mxrp.site"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200